In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1,2,3,4])

print(f"1D array is :{arr_1d}")


arr_2D = np.array([[1,2,3] , [1,23,4]])

print(f"2D array is :{arr_2D}")


1D array is :[1 2 3 4]
2D array is :[[ 1  2  3]
 [ 1 23  4]]


In [ ]:
### List vs numpy Arrays

In [3]:
list  = [1,2,3,4]
print(f"list multiplaction {list * 2}")
np_array = np.array([1,2,3,4])
print(f"Array multiplaction {np_array * 2}")

list multiplaction [1, 2, 3, 4, 1, 2, 3, 4]
Array multiplaction [2 4 6 8]


In [4]:
import time

start = time.time()

print(start)
print('\n')

list = [i*2 for i in range(1000000)]
end = time.time()

print(f"list operation time {end-start}")

start = time.time()
np_array = np.arange(1000000)*2

end = time.time()
print(f"array  operation time {end-start}")





1750142933.6216745


list operation time 0.06899142265319824
array  operation time 0.0056607723236083984


### creating array from scratch


In [5]:
zeros = np.zeros((2, 3))
print("zeros array: \n" , zeros)


once = np.ones((5,3))

print("once array: \n" , once)


full  = np.full((2,3) , 7)
print("full array: \n" , full)


random = np.random.random((2,3))
print("random array: \n" , random)


sequance = np.arange(0 , 11 , 2)
print("sequance array: \n" , sequance)

zeros array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
once array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7 7]
 [7 7 7]]
random array: 
 [[0.54578006 0.95901126 0.06634218]
 [0.65843989 0.07302331 0.38053759]]
sequance array: 
 [ 0  2  4  6  8 10]


vector metxix and tensor

In [6]:
vector = np.array([1,2,3])
print("vector : ",vector)

metrix = np.array([[1,2,4] , [1,2,34]])
print("metrix : " , metrix)

tensor = np.array([[[1,2,3] ,[1,2 , 3]] , [[1,2,3] , [1,2,3]]])
print("tensor : " , tensor)

vector :  [1 2 3]
metrix :  [[ 1  2  4]
 [ 1  2 34]]
tensor :  [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


Array properties


In [7]:
import numpy as np

my_arr = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("shape" , my_arr.shape)
print("Dimenstion" , my_arr.ndim)
print("size" , my_arr.size)
print("Dtype" , my_arr.dtype)


shape (2, 3)
Dimenstion 2
size 6
Dtype int64


Array Reshaping

In [12]:
arr = np.arange(0 , 10)
print(arr)

reshasped = arr.reshape(2,5)
print("Reshaples" , reshasped)

[0 1 2 3 4 5 6 7 8 9]
Reshaples [[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
import numpy as np

arr = np.arange(0, 11)
print("Original array:", arr)

# Reshape
reshaped_1x11 = arr.reshape(1, 11)
reshaped_11x1 = arr.reshape(11, 1)
print("\nReshaped 1x11:\n", reshaped_1x11)
print("Reshaped 11x1:\n", reshaped_11x1)

# Flatten
raveled = reshaped_1x11.ravel()
flattened = reshaped_11x1.flatten()
print("\nRaveled (flattened):", raveled)
print("Flattened:", flattened)

# Properties
print("\nArray Properties:")
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10]

Reshaped 1x11:
 [[ 0  1  2  3  4  5  6  7  8  9 10]]
Reshaped 11x1:
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]

Raveled (flattened): [ 0  1  2  3  4  5  6  7  8  9 10]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10]

Array Properties:
Dimensions: 1
Shape: (11,)
Size: 11
Data type: int64
